on:
  push:
    paths-ignore:
      - "**/*.md"
    branches:
      - 'master'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run the build script
        uses: cake-build/cake-action@v2
        env:
          diadoc_signing_secret: ${{ secrets.DIADOC_SIGNING_SECRET }}
        with:
          target: AppVeyor
          arguments: |
            configuration: Release
          cake-version: 1.3.0
          cake-bootstrap: skip
          verbosity: Diagnostic
  
  
