on:
  push:
    paths-ignore:
      - "**/*.md"
      
jobs:
  build_and_test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 5.0.x

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Run the build script
        uses: cake-build/cake-action@v2
        env:
          diadoc_signing_secret: ${{ secrets.DIADOC_SIGNING_SECRET }}
        with:
          target: Default
          arguments: |
            configuration: Release
          cake-version: 1.3.0
          cake-bootstrap: skip
          verbosity: Diagnostic

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            */bin/Release/*.nupkg
            */bin/Release/*.zip
          if-no-files-found: error
